#!/usr/bin/env python3
"""
Write <out_dir>/validation_report.json: every number recomputed from the files on
disk and from the gates' real exit codes. Nothing is typed in by hand, so the report
can be quoted as-is (and regenerated by anyone).

    python3 scripts/make_validation_report.py                          # US GAAP single-error
    python3 scripts/make_validation_report.py --config configs/ifrs.json
"""
import argparse, collections, glob, json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
from frameworks import get as _fw  # noqa: E402


def run(cmd):
    p = subprocess.run([sys.executable] + cmd, cwd=ROOT, capture_output=True, text=True)
    return p.returncode == 0, (p.stdout.strip().splitlines() or [""])[-1]


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--config", default="config.json")
    a = ap.parse_args()
    cfg = json.load(open(os.path.join(ROOT, a.config)))
    fw = _fw(cfg.get("framework", "us-gaap"))
    out, clean = os.path.join(ROOT, fw["out_dir"]), os.path.join(ROOT, fw["clean_dir"])
    recs = [json.loads(l) for l in open(os.path.join(out, "records.jsonl"))]
    summary = json.load(open(os.path.join(out, "summary.json")))
    inj = [r for r in recs if r.get("record_type") == "injected"]

    # exactly one fault per single-error record: one rule, one injection log
    multi = [r for r in inj if not r.get("rule_id") or not isinstance(r.get("injection_detail"), dict)]
    gate_ok, gate_line = run(["scripts/check_triviality.py", "--config", a.config])
    ident_ok, ident_line = (run(["scripts/identifiability_check.py"]) if fw["out_dir"] == "data/benchmark"
                            else (None, "not run for this framework yet"))
    files = sorted(glob.glob(os.path.join(clean, "*.json")))
    report = {
        "framework": cfg.get("framework", "us-gaap"),
        "config": a.config,
        "companies_in_config": len(cfg["companies"]),
        "companies_targeted": summary.get("companies_targeted"),
        "companies_built": summary.get("companies_built"),
        "companies_skipped": [x for x in summary.get("company_status", []) if x["status"] != "built"],
        "clean_statements_on_disk": len(files),
        "clean_statements_by_type": dict(collections.Counter(f.rsplit("_", 1)[-1][:-5] for f in files)),
        "fiscal_years_present": sorted({int(os.path.basename(f).split("_")[1]) for f in files}),
        "items": len(recs),
        "clean_controls": len(recs) - len(inj),
        "injected": len(inj),
        "single_error_verified": len(inj) - len(multi),
        "single_error_violations": len(multi),
        "citation_tiers": dict(collections.Counter(r["ground_truth_citations"]["citation_tier"] for r in recs)),
        "distinct_citable_paragraphs": len({r["ground_truth_citations"]["asc_full"] for r in inj
                                             if r["ground_truth_citations"].get("citable")}),
        "triviality_gate": {"passed": gate_ok, "last_line": gate_line},
        "identifiability": {"passed": ident_ok, "last_line": ident_line},
        "llm_in_ground_truth_loop": False,
        "accountant_review_of_citations": "not done",
    }
    p = os.path.join(out, "validation_report.json")
    json.dump(report, open(p, "w"), indent=2)
    print(json.dumps(report, indent=2))
    sys.exit(0 if gate_ok and not multi else 1)


if __name__ == "__main__":
    main()
